### PR TITLE
Fixed bugged sign extension within branching

### PR DESCRIPTION
**Pull request by JMcKiern**
To put it briefly, the immediate argument wasn't being correctly sign extended from 16 bit to 32 bit values.

### CODE REVIEW

**Comment by platinum95** [comment]
I think we should use the C++-style `std::cout << std::flush;` rather than the C-style fflush, just to keep the IO consistent.

As for the IMM issue, I think we should split it up over a few more lines just to make it easier to read. The compiler should optimise it down anyways so we shouldn't lose any performance.

One question about it, do we know what order the casting should be done? Currently we're going uint32->int16->int32->bitshift. Should this be uint32->bitshift->int16->int32 instead? Or maybe even some other order? I haven't looked at the docs yet, so not sure.

**Comment by JMcKiern** [comment]
My thinking was that i wanted to flush the buffer of printf. If the buffer is associated with stdout and is shared by printf and std::cout then yeah, std::flush would make more sense 

Not sure what the best method is for the casting but i know that one worked.

Just as an example, if imm is 0xFFF7 (although we have it as 0x0000FFF7). It needs to be converted to 0xFFFFFFF7 (which is why we have int16->int32) and then bit shifted to 0xFFFFFFDC.

Also, the bit shift has to be after the int16->int32 conversion because otherwise the highest 2 bits would be omitted if its bitshifted on int16.

**Comment by platinum95** [comment]
Actually yeah looking at `CPU.c` I've mixed `printf` in with `std::cout` so fflush is a drop in the water here. At some point I'll change the `printf`s to C++-style so no point changing fflush here.

For the other bit I was mainly wondering about a case such as, for example, `imm=0x2FFF`, so that most-significant nybble is `0010`. If we cast to signed int before bit-shifting, it's seen as a positive, but if we bit-shift first that most-significant nybble becomes `1000` which would mean a negative number. Just spitballing here like, I think you're right about the bit-shift needing to come after. In that case I'd say just split that conversion up over one or two more lines just so it's a bit more clear what's going on since 2 immediately-serial casts can be a bit confusing.

**Comment by JMcKiern** [comment]
I'll change the fflush anyway, didn't realise that std::flush would work.

Yeah, I *think* I'm right about the bit shifting order but it might be worth testing that edge case later.

**Comment by platinum95** [comment]
Looks good to me, haven't tested it but I'm sure it's grand

**Pull request merged**
