### PR TITLE
Some minor updates

### PR DESCRIPTION
**Pull request by JMcKiern**

### CODE REVIEW

**Comment by platinum95** [comment]
```/usr/bin/ld: unrecognised option '--stack'```
on Linux, might need some OS-specific guards

**Comment by platinum95** [comment]
Something like
```
ifeq ($(OS),Windows_NT)
    CXXFLAGS +=  --stack,4194304
    CFLAGS +=  --stack,4194304
endif
```
maybe

**Comment by platinum95** [comment]
Compiles for me now so lgtm

**Comment by JMcKiern** [comment]
Sweet

**Pull request merged**
